### ISSUE TITLE
How can i use GPU through your code

### ISSUE THREAD

**Issue by houzhijian** [qijiezhao/py-denseflow#1]
Thanks for your contribution.

I have a question about the GPU use.  How can I use GPU through your code?

I reckon original dense_flow can use GPU to accelerate the speed.

**Comment by leeskyed** [comment]
Same issue~

**Comment by leesky1c** [comment]
Have a look about this. 

[OpenCV using GPU on python](https://stackoverflow.com/questions/48255840/how-does-opencv-use-cv2-umat-to-speed-upi-want-to-use-gpu-to-speed-up-opencv)

It works on me. Good luck!

**Comment by leesky1c** [comment]
Also this one.
[opencv-transparent-api](https://www.learnopencv.com/opencv-transparent-api/)

**Comment by houzhijian** [comment]
@leeskyed Thank you for telling a method to accelerate the speed. I am sad to find out that OpenCV-python has not supported CUDA yet.

**Comment by rrryan2016** [comment]
> 
> 
> Have a look about this.
> 
> [OpenCV using GPU on python](https://stackoverflow.com/questions/48255840/how-does-opencv-use-cv2-umat-to-speed-upi-want-to-use-gpu-to-speed-up-opencv)
> 
> It works on me. Good luck!

heyyyyy, I wanna do some speed-up as well. 

And I read 2 links you have provided, and trying to use `cv2.UMat()`  to accelarate. 

What I did is simply to change https://github.com/qijiezhao/py-denseflow/blob/72854796a53c88132585d782e8788091db5254a9/denseflow.py#L110 into `image = cv2.UMat(frame)`. 

But a TypeError found in https://github.com/qijiezhao/py-denseflow/blob/72854796a53c88132585d782e8788091db5254a9/denseflow.py#L184

Details are here,

```
Traceback (most recent call last):
  File "/media/nopanic/DATA/video_exp/extraction/py-denseflow-master (modified)/denseflow.py", line 201, in <module>
    pool.map(dense_flow,zip(video_list,flows_dirs,[step]*len(video_list),[bound]*len(video_list)))
  File "/home/nopanic/anaconda3/envs/PY27/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/nopanic/anaconda3/envs/PY27/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: 'cv2.UMat' object has no attribute '__getitem__'
```

Could you please give me any advice? Thx :P

**Comment by AugustKarlstedt** [comment]
You can build opencv with python + cuda support. I can confirm it works on 4.1.1-pre
